### ISSUE TITLE
Plotting does not work with pspline()

### ISSUE THREAD

**Issue by dylanpieper** [RobinDenz1/contsurvplot#1]
Plotting with `plot_surv_contour()` and `plot_surv_heatmap()` does not work when using a `pspline()` term such as:
> coxph(Surv(outcome, event) ~ pspline(predictor, 2))

Here is the error produced when you try to use `pspline()`:
> Error in cbind(1, survPred)[, where + 1] : subscript out of bounds

I would like to request, if possible, a feature implementation that allows `pspline()` or to know what alternatives are best.

Thank you!

**Comment by RobinDenz1** [comment]
Thank you for bringing this to my attention. Unfortunately, this is not a bug in the `contsurvplot` package. It's a bug in the `predictRisk.coxph.penal` function of the `riskRegression` package, meaning that I am not in a position to fix this. As i see it, you have the following options:

1.) Use any other spline function, such as `bs()` or `ns()`. This would be my suggestion, as they usually work very well too.
2.) Use polynomial terms instead of splines.
3.) If you are keen on using `pspline`, you could try contacting the maintainers of the `riskRegression` package (ideally with a reproducible example) or manually overwrite the `predictRisk.coxph.penal` function with your own working code.

If you have any further questions or suggestions, please let me know!

**Comment by RobinDenz1** [comment]
I have adressed the `pspline` issue in https://github.com/tagteam/riskRegression/issues/44. A temporary fix to this is to use:
```R
class(model) <- "coxph"
```
before using the contsurvplot functions. A less hacky fix should be created soon.
