### ISSUE TITLE
Applying balancing weights to plot_surv_contour function

### ISSUE THREAD

**Issue by ghost** [RobinDenz1/contsurvplot#4]
I'm attempting to estimate the effect of a continuous variable on survival using the weighted Cox proportional hazard model. However, it appears that the plot_surv_contour function does not support balancing weights. Could you please guide me on how to use balancing weights with this function?

**Comment by RobinDenz1** [comment]
First, I would like to point out that it may not be a good idea to use a weighted cox model in this instance. A simulation study I conducted on this topic (albeit with a categorical treatment variable) indicate that including weights in a cox model - even if correctly estimated - results in biased estimates. See  https://doi.org/10.1002/sim.9681 (in this article I called this method "G-Formula + IPTW"). If I were you, I would include all relevant confounders in the Cox model and would use that directly to create the plot, without using any weights.

That being said, the `plot_surv_contour` function and every other plot function of this package rely on conditional survival probability estimates generated by the `predictRisk` function from the `riskRegression` package. This function calls the `predictCox` function of the same package if a `coxph` model is supplied to it. Currently, that function does not support cox models that have been fitted with weights.

Therefore, if you really do want to use a weighted cox model you would have to overwrite the `predictCox` function with your own function that generates the required survival probability predictions. Otherwise it won't work.

Hope this helps!

**Comment by ghost** [comment]
Thank you for your comment. Due to the limited sample size and the number of events, we cannot include all covariates to create a multivariable Cox regression model. We are reconsidering our approach to resolve this issue so that we can use an unweighted Cox regression model.

**Comment by RobinDenz1** [comment]
I see. One option might be to only include the absolutely most important variables, that have the largest effect on the time-to-event outcome. Either way, good luck with your project!
