### ISSUE TITLE
contsurvplot won't install

### ISSUE THREAD

**Issue by iyannan18** [RobinDenz1/contsurvplot#7]
hello, I used the install.packages("contsurvplot") and get the message it has been downloaded. however when the package does not show on the packages pane and library(contsurvplot) results in and error. thank you!

**Comment by RobinDenz1** [comment]
Since this package is distributed officially by CRAN, the source files and installation procedures are continuously tested as well. Therefore it is very very unlikely that this issue is due to any problems with the package itself. There must be something wrong with your R installation or the way in which you use it. Maybe you install the package to the wrong directory? I recommend searching for a more general solution on google or trying to re-install your R version. Best of luck!
