### ISSUE TITLE
plot_surv_lines x-axis trouble

### ISSUE THREAD

**Issue by rk13111** [RobinDenz1/contsurvplot#9]
Hi,

Thank you for such a wonderful and user-friendly package! I am running into a problem when I use plot_surv_lines(). My data is censored at 730 days (I'm looking at how being born before/after a particular event impacts survival to 2 years of age). Even though I have several individuals who survive to 730 days, my plot_surv_lines graph stops plotting at around 600 days. I can't figure out why this is.

![example](https://github.com/RobinDenz1/contsurvplot/assets/168365791/587f4c7c-5716-42b5-ad19-35011e9c158b)

Here is a reproducible code (with only 10 observations, my actual dataset is much larger):

df<-data.frame(ID=c("1","2","3","4","5","6","7","8","9","10"),
               DaysSurvived=c(0L,32L, 132L,418L,515L, 613L, 730L, 730L,730L,730L),
               Status=c(1L, 1L, 1L,1L,1L,1L,0L,0L,0L,0L),
               MaternalAge=c(1.8L, 0.35L,-1.004L,-0.256L,-1.43L,0.91L,-0.16L,0.71L,-1.2L,-1.1L),
               BirthDate=c(1.09L,1.51L,-0.51L,-1.49L,1.56L,-1.31L, 0.19L,0.92L,-1.23L,0.4L),
               PeakBirthSeason=c("yes","no","yes","yes","no","no","yes","yes","yes","yes"),
               Group=c("A","B","C","C","A","B","C","B","A","A"))

Model<-coxph(Surv(DaysSurvived,Status) ~
                        BirthDate + PeakBirthSeason + MaternalAge + frailty(Group), data=df,x=TRUE)

plot_surv_lines(time="DaysSurvived",
                status="Status",
                variable="BirthDate",
                data=df,
                model=Model,
                max_t = 730,
                horizon= c(-1.7,-0.9,-0.22,0.83,1.68))

I also had a question about one of the warnings I get. I am using a frailty term, and when I use "plot_surv_lines", I get the warning "contrasts dropped from factor frailty(Group)." Does this mean that the graph is just not considering the effects of the frailty term?

Thank you so much for your help.

**Comment by RobinDenz1** [comment]
Thanks for the kind words.

By default, the `plot_surv_lines()` function only presents estimates up to the last observed event time. I implemented it this way because some of my simulation studies suggested that predictions beyond this time are often unstable / biased. If you want to ignore this warning though, you can change the `fixed_t` argument to plot the survival probability at any point in time you would like.

Regarding your second question: Internally the `plot_surv_lines()` function uses the `predictRisk()` function from the `riskRegression` package to perform the required G-computation step (see `?curve_cont` for more information). This in turn calls the simple `predict()` function of the `survival` package when using a `coxph` model with a frailty term. This function is what creates the warning. I am not sure what it means but you may figure it out by looking at the documentation in that package.

**Comment by rk13111** [comment]
Hi Robin,

Thank you so much for your quick reply-- this was very helpful!! I
appreciate it.
